### ISSUE TITLE
Edition of log entries show allow to change the date and time

### ISSUE THREAD

**Issue by GatoMalandra** [sickmartian/trackendar#3]
Hello,

The other day I created an event with the "habit" (second option), so after a few records I wanted to change the mode to "Occurrence" (first option). but there is no such possibility.

It would be great since this option would give more flexibility to the program.

Another idea is the ability to change (correct) the date and time of an event.  For example if I forget to log an event when it happened and record a few hours later.

Regards,
Carlos

**Comment by sickmartian** [comment]
Hi Carlos, thanks for the input.

About the first suggestion, I've had it like that in the past, however the thing is that you can only move up when changing event types when you already have log entries..

         occurrence
         /         \
       habit       value

So you can't move down from occurrence to habit or value, because you don't have a status for each entry or a value for each entry respectively. Also moving between habit and value is not possible for the same reason.
Allowing you to move up as in your example would directly incurr on data loss as well.
You can argue that we can put some sensible defaults, but then it gets tricky and confusing, so it's a no-go for now at least not without some guidance and warnings to the user.

---

I want to start working on the second suggestion ASAP, I've gotten it from other channels as well, and I belive it's the only sensible way to get 'soft' habits (say you do something 3 times a week, M, W and F.. but you did it on Sunday instead of Friday.. you would want to delete the habit with status 'no' from Friday and add it as 'yes' on Sunday today, which is a pain... moving it seems more friendly).

**Comment by sickmartian** [comment]
Okay, here is how it's looking so far:

If you create or modify an entry you get this addition to the common dialogs. Tapping on the date or time will let you select a date or time.
If you edit an event and move it to another day where a reminder was scheduled already, the reminder is consumed and sent to the next day.
![2016-01-24 18_29](https://cloud.githubusercontent.com/assets/492246/12539046/81e9368c-c2c8-11e5-9a81-736219a6a788.png)

On the extended details of the day screen card the time appears, as well as the creation date/time of the entry that was there before.
![2016-01-24 18_31a](https://cloud.githubusercontent.com/assets/492246/12539057/b83f2ae8-c2c8-11e5-9403-2a75b0f57942.png)

On the event overview screen the time appears by default, I took out the creation data, while it's available it makes the screen too "heavy" to read and I don't think it provides a lot of benefit in the first place.
![2016-01-24 18_31c](https://cloud.githubusercontent.com/assets/492246/12539061/c65fb28c-c2c8-11e5-851a-5c8a0beabd84.png)

I still have to change a bit the exported CSV to export also the time.

Let me know what you think.

**Comment by GatoMalandra** [comment]
Excelet

2016-01-24 18:32 GMT-03:00 leuu86@gmail.com <notifications@github.com>:
