### ISSUE TITLE
Recurrence for Habit events

### ISSUE THREAD

**Issue by GatoMalandra** [sickmartian/trackendar#4]
Assume the following case:
I created an event like habit and I created an occurrence only on certain days of the month, For example, I did 20 days and did not do it for 11 days.
When I see the chart, a pie chart appears with 100% done. This is because I do not associate any alarm.
the problem is that I want to look my habit, but I do not want to remind me every day with an beep.
Then, it would be ideal to have the possibility that the alarm is silently (without sound and without notice) and will record the "no ocurrences" (as it is currently done) and the chart show the correct percentages.

**Comment by sickmartian** [comment]
Yeap, we are aware of this.

You really don't want an alarm or reminder, you want to set the recurrence of the habit and for it to auto-update in case you didn't log it in a certain day. There is some work for that already done, but it was halted because alarms are more broadly used and I need to figure out a friendly way to show both recurrence for alarms and for habits when editing the event.

The idea is that if the recurrence day/time passes then the event gets logged automatically in either an undefined status for you to check out later, or as not done, according to how you setup the habit. Additionally you can put reminders over the habit recurrence (or maybe on a separate schedule as well? I haven't decided yet).

I'm changing the name of the issue to reflect this, but let me know if I miss-interpreted what you say and I will change it back.

**Comment by GatoMalandra** [comment]
Hello,

We define 4 types of date:
- Scheduled date: when the event should occur (alarm)
- Date of event: when the event actually occurs
- Date of registration: when the event is recorded in the application
- Update: When any change is made in data record

I think you show the dates:
- Date of event
- Date of registration

For me the most interesting dates to show are:
- Scheduled date
- Date of event
- Date of registration (optional if there is no space)

Overall, Date of event and Date of registration will be the same in many cases.

For me the occurrence of an event is more important than the date of registration and I thank the new functionality to modify the dates.

Regards,
Carlos

**Comment by sickmartian** [comment]
Hi, are you sure your comment is for this issue?

I understand what dates we have yes, but did you mean to start another issue telling me to show some date times in some place in the app (in that case, which part? Day card? Event overview?)? Or how is this related to the 'silent alarm' issue in some way I don't get?

I do agree, the event date/time is more important in general than the registration, which is why it's now editable (or really, possible to set at all). You can see both date/times on the day card (the day is implicit as is in the title of the view), and only the event date/time on the event overview screen.

**Comment by GatoMalandra** [comment]
Sorry, you're right, I prepare a new issue.

2016-02-01 13:48 GMT-03:00 leuu86@gmail.com <notifications@github.com>:

**Comment by sickmartian** [comment]
The Auto-Log is part of the Power User Pack on the 1.7 version.
