### ISSUE TITLE
Problems with dates

### ISSUE THREAD

**Issue by GatoMalandra** [sickmartian/trackendar#6]
Hello team,

I configured two events with alarm

1. Event 1; alarm at 13:20
2. Event 2; alarm at 13:25

I let the time intentionally.

**Event 1:** 
I made the event one at the scheduled time (13:20), but I entered at 15:10

When entering the event  window display the alarm time as default time (13:20), I did not make any changes.

On the extended details of the day screen card the time appears:
Time: 13:20
Created: 15:10

**Even 2:**
I made the event at 14:30 and entered the app at 15:11.

When entering the event  window display the alarm time as default time (13:25), I edit the date and select the time 14:30.

On the extended details of the day screen card the time appears:
Time: 14:20
Created: 15:11

It is correct, but is not very useful

For me it is more useful to look at the scheduled time and time the event actually happened.

Evento 1
Alarm: 13:20
Occurred: 13:20

Evento 2
Alarm: 13:25
Occurred: 14:30

So I can see the delay between scheduled and when it occurred
The date of entry is not really important, but if there is room, would be nice to include

Evento 2
Alarm: 13:25
Occurred: 14:30
Created; 15:11

Regards,
Carlos

**Comment by GatoMalandra** [comment]
I forgot a third case.

Event 3

**Comment by GatoMalandra** [comment]
I forgot a third case

Event 3; alarm at 13:30

Event 1: 
I made the event one at the scheduled time (15:18), and I entered at 15:18

When entering the event window display the alarm time as default time (13:20), I edit the date and select the time 15:18

On the extended details of the day screen card the time appears:
Time: 15:18
Created: 15:18

In most cases, the event is recorded when it occurs so that there could be an option to define what time will be displayed by default,

1. the alarm time
2. the current time

Currently the alarm time is displayed, but for me it would be more practical to the current time, although this depends on user preferences.

Regards
Carlos

**Comment by sickmartian** [comment]
Hi,

About your first two cases, you just want to add the Alarm time to the day card if I understood correctly. This can be done in two ways:
* I just show the current alarm. This is the simplest option.
* On each log entry created by a reminder, I save the current alarm at creation time, if there is any. In case the alarm changes this does not. However, the log entry might be moved now, so then you will need to maybe also know on which day the alarm got triggered and not only the time, which would make it look ugly, but useful.

I'm leaning towards the second option because the first one is not so useful.

About the third case, yes, I made it so the alarm time is used by default when creating an event from the alarm, this can be a setting so you get the option default to 'now'. I will look into it during the week.

By the way, if you want you can send me an email and I can add you to the beta testing team so you can try what we are doing and give feedback. Besides, in case you speak Spanish, we can talk via email in Spanish (not here as someone else might want to pinch in) to further clarify any points.

**Comment by sickmartian** [comment]
I gave it a shot. So, first here is the alarm/reminder extra time.
![Test](https://cloud.githubusercontent.com/assets/492246/12804689/f3f98b74-cad3-11e5-83b6-0cebb46aa845.png)

In the screenshot "Test" has a reminder set, "NoRec" doesn't have any.

A note about this feature: this will only get tracked from the next version onwards, can't work retroactively with already created event entries, as the data is just not there.
Also, I simplified this a bit, omitting the part of 'log entry created by a reminder' and just added it to any log entries, even if it wasn't created by a reminder, and also I omited the part of saving the date, I only save the time of the reminder. As it was too much rework for something that's probably not the intended use-case.

Finally, I'm adding the option to user the current time instead of the pending event, but it's going to be disabled by default as that's the current behavior of the app, else it might confuse current users.

**Comment by GatoMalandra** [comment]
Sounds good second choice, I had not thought of changing the alarm.

Regarding the order, you propose:
Time
remainder
Created

For a chronological aspect would have:
remainder
Time
Created

But your alternative sounds good as the first line (time) would be the most
important

Regards,
Carlos

2016-02-04 0:17 GMT-03:00 leuu86@gmail.com <notifications@github.com>:

**Comment by sickmartian** [comment]
It's on the 1.7 version.
