### ISSUE TITLE
Graphic status for occurrences (pie chart)

### ISSUE THREAD

**Issue by GatoMalandra** [sickmartian/trackendar#8]
Hello,
Now that the occurrences allow auto-log, it would be ideal that could display the graph of State (pie chart). Only if you have enabled auto-log option.

Regards,
Carlos

**Comment by sickmartian** [comment]
Hi Carlos,

Unfortunately this doesn't work, occurrence entries don't have a state and one can't be calculated via the recurrence because the recurrence might change during the life of the event and make the whole thing meaningless.

What probably need to happen here is a conversion between occurrence and habit events, which will take some time to develop.

**Comment by sickmartian** [comment]
Actually I'm trying to develop the conversion right now, would you be interested in beta testing it?

**Comment by GatoMalandra** [comment]
Hello,

Thanks for the offer. I do not have the time it deserves this
responsibility (I am 49 years old jejeje)

Regards,
Carlos

2016-03-18 20:31 GMT-03:00 leuu86@gmail.com <notifications@github.com>:

**Comment by sickmartian** [comment]
No problem, I just sent the conversion anyway. I will close this now. Thanks for your input :+1:
